const Data = [
    {
        title: "웹프레임워크1",
        img: "img/001.jpg",
        vote_average: 100,
        track: "웹공학",
        description: "본 교과목에서는 자바 스프링 프레임워크에 대해 학습한다. 구체적으로, 스프링 개발을 위한 시스템 구축, Maven 활용법, 의존성 주입(dependency injection), JDBC를 이용한 DB 연동, 웹 폼과 스프링 MVC를 이용한 웹 응용 프로그램 작성 방법을 학습한다. 또한 스프링 시큐리티를 활용한 사용자 계정 관리, AOP(Aspect-Oriented Programming) 기술을 소개한다. 본 과정에서는 웹 응용 서버 프로그램을 단계적으로 설계 및 구현하는 프로젝트 기반 접근 방법을 제공한다.",
        section: "major",
        credit: "3학점",
        grade: "3학년",
        favorite: true,
        myList : true,
    },
    {
        title: "가상현실",
        img: "img/002.jpg",
        vote_average: 20,
        track: "모바일소프트웨어,디지털콘텐츠/가상현실",
        description: "멀티미디어 분야의 미래 발전 방향인 가상현실의 이론을 학습하고 실습을 통하여 가상환경 및 Object를 제작한다. 가상현실 시스템인 HMD, Tracker, Data Glove 등의 기술적인 내용을 학습한다.",
        section: "major",
        credit: "3학점",
        grade: "3학년",
        favorite: true,
        myList : true,

    },
    {
        title: "네트워크 프로그래밍",
        img: "img/003.jpg",
        vote_average: 1,
        track: "모바일소프트웨어",
        description: "이 과목은 인터넷의 기반 통신 프로토콜인 TCP/IP프로토콜을 중심으로 현재 사용되고 있는 여러 프로토콜을 이해하고 그 프로토콜을 소프트웨어에서 이용하기 위한 방법론을 배운다. 특히 TCP/IP 의 각 계층별 프로토콜 내용을 패킷 헤더 분석을 통하여 상세하게 이해한다. 또한 클라이언트 서버환경에 필수적인 소켓 프로그래밍 방법을 이해하고, UNIX 및 윈도우즈 환경에서 C, C++, Java 및 Android 프로그램 개발 실습을 통하여 스스로 응용계층 프로토콜을 정의하고 구현함으로써 네트워크 상에서의 소프트웨어 개발에 관한 전 과정을 체험하게 된다. 특히 네트워크 통신 기능을 응용프로그램에서 필요한 공통 모듈로 정형화하고 인터페이스를 정의하며 통합할 수 있는 능력을 배우게 된다.",
        section: "major",
        credit: "3학점",
        grade: "3학년",
        favorite: false,
        myList : true,

    },
    {
        title: "웹서버 프로그래밍",
        img: "img/004.jpg",
        vote_average: 7,
        track: "웹공학",
        description: "웹서비스의 기본적인 구성을 이해하고 아파치 웹서버를 사용하여 운영하는 기법을 학습한다. 특히 웹서비스 언어로 많이 사용되는 PHP 언어의 문법을 학습하고 DB 연동을 통하여 응용하는 방법을 배운다.",
        section: "major",
        credit: "3학점",
        grade: "3학년",
        favorite: true,
        myList : false,

    },
    {
        title: "알고리즘",
        img: "img/005.jpg",
        vote_average: 45,
        track: "모바일소프트웨어",
        description: "어플리케이션을 구현하기에 사용할 수 있는 히프, AVL 트리, 그래프와 같은 고급 자료구조와 관련된 알고리즘을 학습하고, 이들을 실제로 C 프로그래밍 언어 및 IDE(Visual Studio 등) 도구를 활용하여 프로그래밍 하는 방법을 학습한다. 또한, 해싱 기법과 다양한 정렬 알고리즘에 대해서 학습한다.",
        section: "major",
        credit: "3학점",
        grade: "2학년",
        favorite: true,
        myList : false,

    },
    {
        title: "객제지향언어2",
        img: "img/006.jpg",
        vote_average: 87,
        track: "모바일소프트웨어",
        description: "Java는 클래스 기반이며 객체 지향적인 범용 컴퓨터 프로그래밍 언어이다. Java는 개발자들로 하여금 한번 작성한 후 다시 컴파일되는 과정 없이 모든 플랫폼에서 수행될 수 있다. 이 과목에서 Java의 특성과 기법들, Java 언어의 문법과 JDK 라이브러리들, GUI 라이브러리, 그리고 멀티스레드를 작성하는 기법을 소개한다. 실습을 통해 자바 프로그래밍을 연습하도록 하고, 미니 프로젝트를 통해 주어진 문제를 학생 스스로 해결해나가도록 지도한다.",
        section: "major",
        credit: "3학점",
        grade: "2학년",
        favorite: true,
        myList : false,

    },
    {
        title: "모바일&스마트 시스템",
        img: "img/007.jpg",
        vote_average: 98,
        track: "모바일소프트웨어",
        description: "본 교과목에서는 Arduino 하드웨어를 소개하고 프로그래밍하는 기법을 소개한다. 또한 Arduino를 이용한 홈 어플라이언스와 스마트폰을 네트워크로 연결하는 방법을 학습한다. 본 교과목에서는 IoT 관련 프로젝트를 시연하는데, 홈 어플라이언스는 릴레이/블루투스 모듈을 장착하고 안드로이드 앱에 의해 제어된다. 홈 어플라이언스를 제어하는 기능을 확장하여 IoT 서비스를 구축하는 과정을 소개한다.",
        section: "major",
        credit: "3학점",
        grade: "2학년",
        favorite: false,
        myList : false,
    },
    {
        title: "설계패턴",
        img: "img/008.jpg",
        vote_average: 37,
        track: "모바일소프트웨어",
        description: "이 과목에서는 디자인 패턴을 이용하여 소프트웨어 설계를 수행하는 방법을 제공한다. 이를 위해 객체지향 개념을 및 SOLID등을 포함한 소프트웨어 설계 원리를 이해하고 기본적인 UML 모델링을 수행한다. 이를 바탕으로 가장 기본적인 디자인 패턴들의 개념 및 원리를 소개하고 학생들은 이클립스에서 자바로 실습을 수행한다.",
        section: "major",
        credit: "3학점",
        grade: "3학년",
        favorite: false,
        myList : false,
    },
    {
        title: "고급 모바일 프로그래밍",
        img: "img/009.jpg",
        vote_average: 88,
        track: "모바일소프트웨어",
        description: "본 과목에서는 안드로이드에서 기본적인 응용 프로그램을 개발 기술을 학습한 학생들을 대상으로 고급 애플리케이션 개발을 학습한다. 먼저 백그라운드에서 실행되는 서비스인 알림과 방송 수신에 대하여 학습한다. 안드로이드에서 제공하는 기본적인 하드웨어인 위치 인식, 가속 센서 및 환경 센서 인식 기술을 학습하며, 이들를 활용한 애플리케이션 개발 기술을 학습한다. 또한 음성관련 API를 활용하여 음성 관련 애플리케이션 기술을 학습하며, 오디오 및 비디오를 포함하는 멀티미디어 관련 기술을 학습한다. 마지막으로 개발된 애플리케이션을 상용화하는 마켓 등록 과정을 학습한다.",
        section: "major",
        credit: "3학점",
        grade: "3학년",
        favorite: false,
        myList : true,
    },
    {
        title: "빅데이터 기초",
        img: "img/010.jpg",
        vote_average: 65,
        track: "빅데이터",
        description: "본 과목은 빅데이터트랙 학생들을 대한으로 빅데이터에 대한 전반적인 이해를 높이는 초점을 맞춘다. 구체적으로 인공지능, 머신러닝, 빅데이터, 데이터 기초 등의 분야를 다룬다.",
        section: "major",
        credit: "3학점",
        grade: "2학년",
        favorite: false,
        myList : false,
    },
    {
        title: "시스템 프로그래밍",
        img: "img/011.jpg",
        vote_average: 59,
        track: "모바일소프트웨어",
        description: "리눅스 운영체제의 구조를 이해하고 시스템 호출을 이용한 시스템 프로그래밍 기술을 배운다. 우선 리눅스를 설치하고 관리하는 명령어들을 익힌다. 이를 바탕으로 커널 구조를 이해하고, 파일시스템과 프로세스 관리를 위한 프로그래밍 기술을 배운다.",
        section: "major",
        credit: "3학점",
        grade: "3학년",
        favorite: false,
        myList : true,
    },
    {
        title: "인공지능",
        img: "img/012.jpg",
        vote_average: 36,
        track: "정보시스템",
        description: "인공지능에서의 문제해결을 위한 기법들과 효율적인 탐색방법, 지식의 표현과 처리를 위한 다양한 기법들을 다룬다. 불확실성하에서의 추론, 퍼지이론, 지식 베이스를 이용하는 전문가 시스템, 기계학습, 신경망 이론, 지능형 에이전트 등에 대한 기본적인 내용을 공부하고 관련분야에 대한 실습을 병행한다.",
        section: "major",
        credit: "3학점",
        grade: "4학년",
        favorite: false,
        myList : false,
    },
    {
        title: "K-댄스",
        img: "img/013.jpg",
        vote_average: 0,
        track: "선필교",
        description: "K-dance 실기수업으로 진행되며 K-pop 안무의 기본이 되는 실용무용 동작들의 기본기를 익히고 실용무용 안무를 습득한다.",
        section: "general",
        credit: "3학점",
        grade: "3학년",
        favorite: false,
        myList : false,
    },
    {
        title: "글로벌 노마드와 여행",
        img: "img/014.jpg",
        vote_average: 0,
        track: "선필교",
        description: "이 과목은 세계화와 여행, 이주의 시대를 살아가고 있는 우리들에게 여행이란 무엇인가? 라는 질문을 인문학적, 사회과학적 주제와 사례연구를 통해 이해하고자 한다. 글로벌 노마드 문화로서 세계 각 지역의 특수한 문화변동 과정을 이해하고 문화간 교류와 협력, 지속가능한 관광과 대안적 삶을 찾아가는 사람들의 이야기를 통해 새로운 삶의 스타일과 가능성을 찾는 작업이다.",
        section: "general",
        credit: "3학점",
        grade: "전학년",
        favorite: false,
        myList : false,
    },
    {
        title: "응급구조와 안전관리",
        img: "img/015.jpg",
        vote_average: 0,
        track: "선필교",
        description: "본 수업은 안전관리 및 응급상황 대응방법에 대한 학습을 통하여 다양한 상황에서 발생할 수 있는 사고를 예방하고 이에 대처할 수 있는 능력을 길러 안전에 대한 높은 의식을 갖게 하는 것을 목적으로 한다.",
        section: "general",
        credit: "3학점",
        grade: "전학년",
        favorite: false,
        myList : false,
    },
    {
        title: "사건으로 본 역사",
        img: "img/016.jpg",
        vote_average: 0,
        track: "선필교",
        description: "본 강의에서는 동아시아 역사 속 주요 사건을 선별하여, 이것이 일어난 역사적 배경과 사건의 실체, 그리고 이것이 그 후 역사에 미친 영향을 고찰함으로써 역사를 다양한 시각에서 이해해보는 시간을 가질 예정이다. 동아시아사, 나아가 세계사에 영향을 미친 굵직한 사건들이 많이 있지만, 그중에서도 동아시아 문명의 원류를 제공했던 중국의 역사가 중심이 될 것이다. 물론 문명의 중심이었던 ‘중화’의 세계가 그 ‘주변’ 지역과 역사적으로 어떻게 관계를 맺어왔는지 살펴보기 위해 한국 및 일본, 중앙아시아 세계의 이야기도 언급될 수 있다.",
        section: "general",
        credit: "3학점",
        grade: "전학년",
        favorite: true,
        myList : true,
    },
    {
        title: "사랑과 가족",
        img: "img/017.jpg",
        vote_average: 0,
        track: "선필교",
        description: "사랑, 결혼, 가족의 세 가지 테마를 중심으로 각 내용들을 심도 있게 다룬다. 즉, 성숙한 사랑, 현명한 결혼, 건강한 가족을 형성하기 위해 필요한 기본 지식을 습득하고, 자신을 반추해보며 이해하는 시간을 갖는다.",
        section: "general",
        credit: "3학점",
        grade: "전학년",
        favorite: false,
        myList : false,
    },
    {
        title: "우리 시대의 문학 읽기",
        img: "img/018.jpg",
        vote_average: 0,
        track: "선필교",
        description: "우리 시대에 ‘문학’은 ‘영상’에 밀린 것처럼 보인다. 영상은 남이 만든 그림을 그냥 보여주는 것이고, 관객인 나는 그냥 보기만 하면 된다. 그러나 문학은 남의 작품을 읽고 독자인 내가 나만의 그림을 그려야 한다. <우리시대의 문학읽기>는 말 그대로 다양한 장르의 문학작품을 읽고 나만의 그림을 그려보기 위한 수업이다. 이를 통해 나의 창의적인 생각, 개성적인 생각들을 키울 수 있는 힘을 기르고, 그것을 말과 글로 표현하는데 집중한다. 이 수업을 통해 독서는 힘이 세다는 것을 체감할 수 있기를 기대한다.",
        section: "general",
        credit: "3학점",
        grade: "전학년",
        favorite: false,
        myList : false,
    },
    {
        title: "공감 클래식",
        img: "img/019.jpg",
        vote_average: 0,
        track: "선필교",
        description: "클래식이란, 서유럽에서 유행한 음악의 한 장르로 그 당시의 ‘유행가’라 할 수 있다. 클래식은 우리와 거리가 멀게만 느껴지지만, 이는 우리의 보편적 감성과 맞닿아 있다. 현대의 영화, 방송, 광고에서 클래식 음악이 끊임없이 차용되는 것이 이를 방증한다. 이 강좌는 한편으로는 클래식 예술가들의 삶이나 악기들의 개성을 알고, 다른 한편으로는 시각중심 문화에 다져진 시회에서 청각적 즐거움을 통해 공감각적 감성을 회복하는 것을 목적으로 한다.",
        section: "general",
        credit: "3학점",
        grade: "전학년",
        favorite: false,
        myList : false,
    },
    {
        title: "영미 고전 읽기",
        img: "img/020.jpg",
        vote_average: 0,
        track: "선필교",
        description: "이 강좌는 우리 시대의 눈으로 영미의 고전문학작품을 다시 읽는 것을 목표로 한다. 이 강좌를 통해 문학 읽기의 즐거움을 경험하고 고전문학 작품의 현재성을 확인할 수 있을 것이며, 더불어 우리 시대의 핵심적 쟁점들에 대해서 함께 성찰하고 토론하는 기회를 갖게 될 것이다. 이번 학기에 다룰 작품은 영문학의 자랑이자 대표적 고전인 윌리엄 셰익스피어의 『햄릿』과 20세기 가장 뛰어난 공상과학소설이자 3대 디스토피아 소설로 평가받는 올더스 헉슬리의 ?멋진 신세계?이다. 이 강좌에서는 ‘복수’와 ‘SF’라는 주제를 중심으로, 두 고전 작품이 이후 인류의 상상력에 어떤 영향을 미치고 변주되었는지, 그리고 그 변주를 통해 자신의 시대에 대한 어떤 탐색을 하고 있는가를 살펴볼 예정이다. 영화, 노래 파일, 그림 등 다양한 시각 자료를 사용할 예정이며, 강의가 주가 되겠지만 발표와 조별 토론을 통해 학생들의 적극적인 수업 참여를 유도할 생각이다.",
        section: "general",
        credit: "3학점",
        grade: "전학년",
        favorite: false,
        myList : false,
    },
    {
        title: "심리학으로 세상 읽기",
        img: "img/021.jpg",
        vote_average: 0,
        track: "선필교",
        description: "과학적 방법으로 사람의 심리를 파악하는 융합적 시각의 심리학 기본적 원리를 학습하여, 사람과 세상간의 관계를 해석하는 심리학을 명확히 학습하고, 이를 바탕으로 자신과 타인, 그리고 세상을 해석해보고 자신에게도 적용해 보고자 함.",
        section: "general",
        credit: "3학점",
        grade: "전학년",
        favorite: false,
        myList : true,
    },
    {
        title: "전쟁과 스토리텔링",
        img: "img/022.jpg",
        vote_average: 0,
        track: "선필교",
        description: " 전쟁은 참전집단 간에 승리를 위한 극한의 노력이 강요된다. 따라서 전쟁 수행과정에서 인류생활사에 영향을 주는 요소들이 많다. 이 요소들은 부정적 현상만 있는 것은 아니다. 전쟁은 많은 희생을 유발하지만 인류 문명 발전을 촉진하는 역할도 한다. 과거와 현재의 생활 속에 담겨 있는 전쟁으로부터의 영향을 발견하고 고찰한다. 서적 읽고 토론하기 : 대면 수업 (주당 75분)에서 시행한다.",
        section: "general",
        credit: "3학점",
        grade: "전학년",
        favorite: true,
        myList : false,
    },
    {
        title: "상상력 이노베이터",
        img: "img/023.jpg",
        vote_average: 0,
        track: "선필교",
        description: "영화와 심리학 등의 학문적 이론을 바탕으로 미래사회에 주요 이슈를 논의하고 이에 대해 여러가지 시각과 해결책을 팀 토론과 활동을 통해 논의하고자 함. (영화와 심리학을 바탕으로 한 사 회이슈+ 창의적 문제해결 수업)",
        section: "general",
        credit: "3학점",
        grade: "전학년",
        favorite: false,
        myList : false,
    },
    {
        title: "자연계에 숨은 물리법칙",
        img: "img/024.jpg",
        vote_average: 0,
        track: "선필교",
        description: "본 과목은 우리의 일상 생활에서 접할 수 있는 자연현상의 원리를 과학 법칙과 개념으로 설명할 수 있는 능력을 함양시키는 것을 목적으로 하고 있다. 또한 과학기술 관련 사회적 이슈에 대해 다른 사람들과 의사소통할 수 있는 과학적 소양을 함양시킬 수 있다.",
        section: "general",
        credit: "3학점",
        grade: "전학년",
        favorite: true,
        myList : false,
    }
];

export default Data;